eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5

server:
  port: ${PORT:${SERVER_PORT:9010}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8010/eureka/
  instance:
    preferIpAddress: true