---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/
server:
  port: ${PORT:${SERVER_PORT:9010}}   # Select any available port if neither port nor server port are specified.

---
spring:
  profiles: production

---
spring:
  profiles: development

---
spring:
  profiles: test